const TYPES = {
    GET_PRODUCTS: 'GET_PRODUCTS',
    RESET_PRODUCTS: 'RESET_PRODUCTS',
    GET_DEPARTMENTS: 'GET_DEPARTMENTS',
    RESET_DEPARTMENTS: 'RESET_DEPARTMENTS',
    GET_PRODUCTS_BY_CATEGORY: 'GET_PRODUCTS_BY_CATEGORY',
    ADD_SHOPPING_CART: 'ADD_SHOPPING_CART',
    CHANGE_SHIPPING_ADDRESS: 'CHANGE_SHIPPING_ADDRESS',
    CHANGE_PAYMENT_METHOD: 'CHANGE_PAYMENT_METHOD',
    RESET_SHOPPING_CART: 'RESET_SHOPPING_CART',
    DELETE_PRODUCT_SHOPPING_CART: 'DELETE_PRODUCT_SHOPPING_CART',
    MODIFY_QTY_PRODUCT_SHOPPING_CART: 'MODIFY_QTY_PRODUCT_SHOPPING_CART'
}

export default TYPES;